version: "3"
services:
  database:
    build: postgres:latest
    image: "social-database"
    restart: always
    volumes:
      - ~/social-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=social_username
      - POSTGRES_PASSWORD=social_password
      - POSTGRES_DB=social_database
    networks:
      - social_network

networks:
  social_network:
