spring:
  datasource:
    url: jdbc:postgresql://{DBHOSTNAME:localhost}:5531/social
    username: docker
    password: docker
    hikari:
      minimum-idle: 1

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      format_sql: true

logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        data: DEBUG
    com.social: DEBUG

