spring:
  datasource:
    url: jdbc:postgresql://localhost:5531/social
    username: docker
    password: docker
    hikari:
      minimum-idle: 1
  
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        data: DEBUG
    com.social: DEBUG

