spring:
  datasource:
    url: jdbc:postgresql://${DBHOSTNAME:localhost}:5531/social_database
    username: social_username
    password: social_password
    hikari:
      minimum-idle: 1

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      format_sql: true

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        data: INFO
        security: DEBUG
    com.social: DEBUG

