version: "3"
services:
  database:
    build: postgres
    image: "social-database"
    restart: always
    volumes:
      - ~/social-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=social
    networks:
      - social

networks:
  social:
